config/routes.rb
Rails.application.routes.draw do
 resources :static_pages, only: [:index, :new, :create]   
    get root 'static_pages#index'
    
    get 'static_pages/sharkoWires'
    
    get 'static_pages/greatmoods'
    
    get 'static_pages/spokinResearch'
    
    get 'static_pages/render_dev' 

    get 'static_pages/render_design' 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/static_page.rb
class StaticPage < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Let's talk more about the open position!",
      :to => "erbogart28@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController  < ApplicationController
    layout "homelayout"
end

app/controllers/render_design_controller.rb
class RenderDesignController < ApplicationController
    def render_design
        respond_to do |format|               
        format.js
        end 
    end 
end

app/controllers/render_dev_controller.rb
class RenderDevController < ApplicationController
    def render_dev
        respond_to do |format|               
        format.all
        end    
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    layout "homelayout", only: [:index]
    def index
        @contact = StaticPage.new(params[:static_page])
    end
    
    def spokinResearch
       render layout: "application"
    end
    
    def greatmoods
        render layout: "application"
    end
    
    def new
        @contact = StaticPage.new
    end

    def create
        @contact = StaticPage.new(params[:static_page])
        @contact.request = request
        respond_to do |format|
        if @contact.deliver
            # re-initialize Home object for cleared form
            @contact = StaticPage.new
            format.html { render 'index'}
            format.js   { flash.now[:success] = @message = "Thank you for reaching out. I will email you back soon!" }
        else
            format.html { render 'index' }
            format.js   { flash.now[:error] = @message = "Message did not send." }
        end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def is_active(action)       
        params[:action] == action ? "active" : nil        
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/landing/home.html.erb
<section class="landing">
    <article class="container" id="animatedtext">
        <div class= "row" id="">
            <p id="landing-header" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&mdash; Web developer &mdash;<span>Hi, I'm Evan! </span> &mdash; UI/UX Designer &mdash;</p>
        </div>
    </article>
    
    <article class="container" id="navcircles">
        <div class="row" id="circles-row">      
            <a id="circle-dev" href="/static_pages/development" role="button" class=" btn btn-primary btn-circle btn-xl col-sm-3 col-sm-pull-1 col-md-3 col-md-pull-1 col-lg-3 col-lg-pull-2 vcenter"><span class="navcircle-text">Development</span></a>
            <a id="circle-design" href="/static_pages/design" role="button" class="btn btn-primary btn-circle btn-xl col-sm-4 col-md-4 col-lg-2 vcenter"><span class="navcircle-text">Design</span></a>
            <div id="circle-active" role="button" class="scroll-button btn btn-primary btn-circle btn-xl col-sm-3 col-sm-push-1 col-md-3 col-md-push-1 col-lg-3 col-lg-push-2 vcenter"><span id="original-text" class="navcircle-text hidden-xs <%=is_active('#')%>"><a href="#" address="true">About Me</span></a>       
            <a class="scroll-down container-fluid hidden-lg hidden-md hidden-sm <%=is_active('#')%>" href="#" address="true"><span id="mobile-indicator" class="navcircle-text hidden-lg hidden-md hidden-sm <%=is_active('#')%>">About Me<span class="click-to-scroll">Click to<br>Scroll</span></span>
            <div id="mobile-scroll-btn" class="arrow-scroll-btn"></div>
        </a></div>
        </div>
    
        <!--<div id="ufo" class="scroll-down orbits container-fluid"> <span id="ray" style=""></span></div> <!-- UFO -->
    </article>
    
    <article id="scrolldown-button-row container hidden-xs">
        <div class="row hidden-xs">
            <a class="scroll-down hidden-xs visible vcenter" href="#" address="true">
                <div class="arrow-scroll-btn hidden-xs"></div>
            </a>
        </div>
    </article>
</section>

<section class="aboutme-content">
    
    <div class="container" id="page-title">
        <h1 class="heading">About Me</h1>
    </div>

    <article id="aboutMe" class="row-fluid">
        <div class="container-fluid"> 
            <section class="col-lg-5 col-lg-push-1 col-md-4 col-md-offset-1 col-sm-5"> 
                <%= image_tag("headshot1.jpg", class: "img-responsive center-block", :id => "headshot" )%>
            </section>
            <section class="col-lg-5 col-lg-pull-1 col-md-6 col-sm-6" id="aboutMeText">
                <p>Hello there! My name is Evan R Bogart. I'm a recent DePaul University graduate, where I majored in Interactive and Social Media (ISM for short) with a Development Concentration. Most of my work on this site will be comprised of projects I worked on throughout my 2 &frac12; years at DePaul University. I consider myself a fun-loving coder, and an admirer of design - specifically web/application/software design! Besides coding I enjoy playing video games, watching esports/sports in general, hiking, fishing, and hanging out with friends and family.</p>
                <p>As an ISM major with a Development Concentration, I focused a lot on the front-end. ISM mostly taught me about modern UI/UX design principles and heuristics, which can be very useful to know when evaulating, designing, or developing a site/application. I am very comfortable developing front-end solutions and fully responsive websites using HTML5, CSS3, and JavaScript/jQuery. I have extensive use with Bootstrap, and I'll tend to heavily utilize utility classes to setup a quick and easy grid system.</p> 
                <p>I love Ruby-on-Rails! It's the first MVC framework I learned for web development, and I feel fully confident in coding the front-end for a Ruby-on-Rails web application. I know my way around the Ruby-on-Rails MVC framework, and I'm not scared to utilize the whole spectrum of the framework to correctly implement partials, views, and layouts. Though, when it comes down to it all, I fell in love with this framework because it allows me to work with ".erb" files - my exact initials. &#128516;</p>   
            </section>
        </div>
    </article>

   <article class="container"  id="homepageCards">
        <div class="row">
            <div class="col-xs-12 col-sm-4">
                <div class="card">
                    <div class="card-content">
                        <h4 class="card-title">
                            Contact Me
                        </h4>
                        <div class="contactText">
                            <p>If you have any questions, please feel free to email me!</p>
                            <p><b>Email:</b> erbogart28@gmail.com</p>
                            <p><i>Check out my linkedin</i><a type="button" class="btn btn-block btn-lg btn-linkedin" target="blank_"><i class="fa fa-linkedin"></i></a></p>
                            <p><i>Check out my github</i><a href="https://github.com/erbogart28" type="button" class="btn btn-block btn-lg btn-github" target="blank_"><i class="fa fa-github"></i></a></p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-push-4 col-md-push-4 col-sm-push-4 col-xs-12 col-sm-4">
                <div class="card">
                    <div class="card-content">
                        <h4 class="card-title">
                            View My Resume
                        </h4>
                        <p class="resumeText">
                           My resume can be viewed here. Please feel free to right click the link and save a copy for yourself if you're interested.
                        </p>
                    </div>
                    <div class="card-read-more">
                        <%= link_to " View Resume", image_path("resume.jpg"), :target => "_blank", :class => "btn btn-link btn-block" %>
                    </div>
                </div>
            </div>
        </div>
    </article>
 </section>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>.ERB Portfolio</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'pray_favi.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  <script>//back page where user last left off
    function backPage() {
      window.history.back();
    }
  </script>
  
  <style>
    @import url('https://fonts.googleapis.com/css?family=Roboto:400,700');
  </style>
</head>

<body>
<%= yield %>
<%= render 'footer' %>
<!-- required jquery/JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/homelayout.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>.ERB Portfolio</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'pray_favi.ico' %>
    <meta name = "author" content = "[Evan Bogart]">
    <meta name= "viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Roboto:400,700');
    </style>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  
  <body class="scroll-area" data-spy="scroll" data-target="#sidebar">
  <%= yield %>

    <script>
      $(document).on("turbolinks:load", function() {
       // remove down arrow / scrolldown button if window is scrolled down from the top of page -- only visible if 0 scroll 
          $(function showHideScrollArrow() {
            var w = $(window);
            w.scroll(function () {
              if (w.scrollTop() !== 0) {
                $('.scroll-down').removeClass('visible'); // scroll down becomes hidden, and begins animation out of view, below about me section 
                return;
              }
              $('.scroll-down').addClass('visible'), // will add visible if user SCROLLS BACK TO TOP after a page load | Without this - will not be visible again if scrolled from top
              $('.scroll-down').css('opacity', '1');
            });
            $('.scroll-down').addClass('visible');  // line repeated here for INITIAL PAGE LOAD for landing page | Without this - will not load as a visibile; also, allows for animation on page load without adding visible to scrolldown class
          });//end showHideScrollArrow
          
          // add sidebar when user is outside of landing page section
          $(function showSideBar() {
            var sidebar = $('#sidebar');
            var landingpage_end  = $('#landingPageSection').offset().top +$('#landingPageSection').height()-41; //meausre height of landing page -- red next line for -25 reasoning
            //landingpage_end equation is giving correct screen height results, BUT would sometimes show sidebar too far down in aboutme section (maybe due to scrolldown below landing section - having a hidden height to landing page ?). Added -25 for some cushion, and all mobile screen sizes show the sidebar fine now.
              $(window).scroll(function() {  //pixels from top
                var scroll2 = $(window).scrollTop();
                if (scroll2 <=  landingpage_end ) {
                    sidebar.addClass('hidden') //hide sidebar if scroll position is within landing page
                     $('#scrollup').addClass('hidden');
      
                } else {
                    sidebar.removeClass('hidden'), //show sidebar once scrolled outside of landing page section completely
                      $('#scrollup').removeClass('hidden');
                  }
              });
          });//end show sidebar
          
          //toggle tooltip on hover. Destroy tool tip on mobile screen sizes - allows for single click on mobile screen widths - as opposed to simply hiding w/ css
          $(function (){
            if ( $(window).width() < 760 ){
              $('li').tooltip('destroy'); //remove toolbars from sidebar to avoid complications with touch screen users.
            }else {
                $('[data-toggle="tooltip"]').tooltip({trigger:'hover'}); // basic hover for toolbar
            }
          });
     
          // smooth scrolling to sections // adds ACTIVE class to sidebar depending on sections
          $(function smoothScroll() {
      		  $('.sectionScroll a[href*="#"]:not([href="#"])').click(function() {  //only section scroll links. NO empty links
      			if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {  // On-page links
      			  var target = $(this.hash);
      			  target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      			  if (target.length) {
      				$('html, body').animate({
      				  scrollTop: target.offset().top //animate to target section and stop once section top is at 0
      				}, 1000);
      				return false;
      			  }
      			}
      		  });
      		});// end smoothScroll function
      		//Load both partials on page load - allows for sections to be filtered out properly by rendering on page load
        $('#fill-in').html("<%= escape_javascript(render :partial => 'devWork') %>").append("<%= escape_javascript(render :partial => 'design') %>") && $('#design-filter').toggleClass('hidden') && $('#design-filter-xs').toggleClass('hidden-xs'); 
      });   // end turbolinks on load  
    </script>
    <!-- function for BOTH filter button click - renders partials in div id fill-in when button is clicked. Design filter buttons toggled to hidden to avoid both sections having the same filter choices -->
    <script>  
      function fillboth() {
        $('#fill-in').html("<%= escape_javascript(render :partial => 'devWork') %>").append("<%= escape_javascript(render :partial => 'design') %>") && $('#design-filter').toggleClass('hidden') && $('#design-filter-xs').toggleClass('hidden-xs');
      } 
    </script>
    <!-- required jquery/JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/mail_form/contact.erb
<h4 style="text-decoration:underline"><%= message.subject %></h4>

<% @resource.mail_form_attributes.each do |attribute, value|
  next if value.blank? %>

  <p><b><%= @resource.class.human_attribute_name(attribute) %>:</b>
  <%= case value
    when /\n/
      raw(simple_format(h(value)))
    when Time, DateTime, Date
      I18n.l(value)
    else
      value
    end
  %></p>
<% end %>

<% unless @resource.class.mail_appendable.blank? %>
  <br /><h4 style="text-decoration:underline"><%= I18n.t :title, :scope => [ :mail_form, :request ], :default => 'Request information' %></h4>

  <% @resource.class.mail_appendable.each do |attribute|
    value = @resource.request.send(attribute)
    value = if value.is_a?(Hash) && !value.empty?
      list = value.to_a.map{ |k,v| content_tag(:li, h("#{k}: #{v.inspect}")) }.join("\n")
      content_tag(:ul, raw(list), :style => "list-style:none;")
    elsif value.is_a?(String)
      value
    else
      value.inspect
    end
  %>

    <p><b><%= I18n.t attribute, :scope => [ :mail_form, :request ], :default => attribute.to_s.humanize %>:</b>
    <%= value.include?("\n") ? simple_format(value) : value %></p>
  <% end %>
  <br />
<% end %>

app/views/static_pages/_contact_form.html.erb
<div class="card-content" id="email-form">
  <%= simple_form_for @contact, url: static_pages_path, :html => {:class => 'form-horizontal' }, remote: true do |f| %>
    <%= f.input :name, :required => true, label: 'Your Name / Employer' %>
    <%= f.input :email, :required => true, label: 'Your Email' %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div class="row-new">
      <%= f.button :submit, 'Send Email', :class => 'btn btn-primary col-xs-12 col-md-8 col-md-offset-2', :style => 'margin-top:1rem' %>
    </div>
  <% end %>
</div>
<!-- render flas messages beneath submit button and within the card -->
<div class="" id="flash-message">
  <%= render 'flash' %>
</div>

app/views/static_pages/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/static_pages/_footer.html.erb
<footer class="footer">
      <div class="container">
        <p class="text-muted">
          © 2017 .ERB Portfolio 
          <%= link_to "Back to Top", '/', :class => 'btn-link pull-right' %>
        </p>
      </div>
</footer>

app/views/static_pages/_landing.html.erb
<section class="landing container-fluid" id="landingPageSection"><!-- Landing Page -->
    <div class="row-new" id="landing-header-wrap"><!-- main header on landing page -->
        <p id="landing-header" class="col-xs-12">&mdash; Web developer &mdash;<span>Hi, I'm Evan! </span> &mdash; UI/UX Designer &mdash;</p>
    </div><!-- END main header text container -->
    
    <div class="fade-in" id="landingPageRows"><!-- article wrap for Row sections -->
        <section class="row sectionScroll" id="aboutRowLanding">
            <%= link_to "About Me", '#aboutme-content', :class => 'landingRowButton' %>
            <!-- shooting stars / CSS animations used for star movements -->
            <span class="star1 hidden-xs"></span>
            <span class="star2 hidden-xs"></span>
            <span class="star3 hidden-xs"></span>
        </section>
        
        <section class="row sectionScroll" id="devRowLanding">
            <%= link_to "Dev Work", '#dev-content', :class => 'landingRowButton' %>
        </section>
        
        <section class="row sectionScroll" id="designRowLanding"> 
            <%= link_to "UI/UX Work", '#design-content', :class => 'landingRowButton' %>
        </section>
    </div>
    
    <section id="scrolldown-button-row"  class="sectionScroll" ><!-- Arrow down scroll down button - Scrolls to ABOUT ME section of page -->
        <a class="scroll-down" href="#aboutme-content">
            <span class="arrow-scroll-btn"></span>
        </a>
    </section><!-- end scroll down container -->
</section><!-- END LANDING page section -->

app/views/static_pages/_sidebar.html.erb
<nav id="sidebar" class="hidden">
    <ul class="nav" id="sidebar-nav">
      <li id="aboutSidebar"  class="sectionScroll" data-toggle="tooltip" title="About Me" data-placement="right"><%= link_to "", '#aboutme-content', :class => 'fa fa-2x fa-info-circle' %></li>
      <li id="devSidebar"  class="sectionScroll" data-toggle="tooltip" title="Development" data-placement="right"><%= link_to "", '#dev-content', :class => 'fa fa-2x fa-keyboard-o' %></li>
      <li id="designSidebar"  class="sectionScroll" data-toggle="tooltip" title="Design" data-placement="right"><%= link_to "", '#design-content', :class => 'fa fa-2x fa-universal-access' %></li>
    </ul>
</nav>

app/views/static_pages/create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/static_pages/home.html.erb
<section class="landing">
    <article class="container" id="animatedtext">
        <div class= "row" id="animatedtext-cols">
            <p id="landing-header" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&mdash; Web developer &mdash;<span>Hi, I'm Evan! </span> &mdash; UI/UX Designer &mdash;</p>
        </div>
    </article>
    
    <article class="container-fluid" id="navcircles">
        <div class="row">  
            <ul id="circles-row">
                <li class="navcircle" id="circle-dev"><%= link_to "Development", root_path, :class => "overlay1 col-sm-4 col-md-3 btn btn-primary btn-circle navcircle-text" %></li>
                <li class="navcircle " id="circle-design"><%= link_to "UI/UX Design", root_path, :class => "overlay2 col-sm-4 col-md-3 col-md-push-1 btn btn-primary btn-circle navcircle-text" %></li>
                <li class="navcircle" id="circle-active"><%= link_to "About Me", root_path, :class => "overlay3 col-sm-12 col-md-3 col-md-push-2 btn btn-primary btn-circle  navcircle-text" %></li>
            </ul>
        </div>
    </article>
    
    <article id="scrolldown-button-row"  class="container" >
        <div class="row">
            <a class="scroll-down" href="#" address="true">
                <div class="arrow-scroll-btn"  data-toggle="tooltip" data-placement="top" title="About Me Section" ></div>
            </a>
        </div>
    </article>
</section>

<section id="aboutme-content">
        
        <div class="page-header container"> <!-- page header | heading class adds font styles -->
            <h1 class="heading">About Me</h1>
        </div>
    
    
        <article id="aboutMe" class="row-fluid">
            <div class="container-fluid"> 
                <div class="col-lg-5 col-lg-push-1 col-md-4 col-md-offset-1 col-sm-5"> 
                    <%= image_tag("headshot1.jpg", class: "img-responsive center-block", :id => "headshot" )%>
                </div>
                <div class="col-lg-5 col-lg-pull-1 col-md-6 col-sm-6" id="aboutMeText">
                    <p>Hello there! My name is Evan R Bogart. I'm a recent DePaul University graduate, where I majored in Interactive and Social Media (ISM for short) with a Development Concentration. Most of my work on this site will be comprised of projects I worked on throughout my 2 &frac12; years at DePaul University. I consider myself a fun-loving coder, and an admirer of design - specifically web/application/software design! Besides coding I enjoy playing video games, watching esports/sports in general, hiking, fishing, and hanging out with friends and family.</p>
                    <p>As an ISM major with a Development Concentration, I focused a lot on the front-end. ISM mostly taught me about modern UI/UX design principles and heuristics, which can be very useful to know when evaulating, designing, or developing a site/application. I am very comfortable developing front-end solutions and fully responsive websites using HTML5, CSS3, and JavaScript/jQuery. I have extensive use with Bootstrap, and I'll tend to heavily utilize utility classes to setup a quick and easy grid system.</p> 
                    <p>I love Ruby-on-Rails! It's the first MVC framework I learned for web development, and I feel fully confident in coding the front-end for a Ruby-on-Rails web application. I know my way around the Ruby-on-Rails MVC framework, and I'm not scared to utilize the whole spectrum of the framework to correctly implement partials, views, and layouts. Though, when it comes down to it all, I fell in love with this framework because it allows me to work with ".erb" files - my exact initials. &#128516;</p>   
                </div>
            </div>
        </article><!-- end aboutme article -- content pertaining to me -->
    
    
    
    <article id="homepageCards">
        <div class="row">
            <div class="col-md-4 col-sm-8 col-sm-push-2">
                <div class="card">
                    <div class="card-content">
                        
                        <div class="card-title">
                           Contact Me
                        </div>
                        
                        <div class="contactText">
                            <p>If you have any questions, please feel free to email me!</p>
                            <p><b>Email:</b> erbogart28@gmail.com</p>
                            <p><i>Check out my linkedin</i><a type="button" class="btn btn-block btn-lg btn-linkedin" target="blank_"><i class="fa fa-linkedin"></i></a></p>
                            <p><i>Check out my github</i><a href="https://github.com/erbogart28" type="button" class="btn btn-block btn-lg btn-github" target="blank_"><i class="fa fa-github"></i></a></p>
                        </div>
                         
    
                    </div>
                </div><!--end card -->
            </div><!-- end column div -->
    
            
    
            <div class="col-md-4 col-sm-8 col-sm-push-2">
                <div class="card">
                    <div class="card-content">
                            <div class="card-title">
                                View My Resume
                            </div>
                            <div class="resumeText">
                                <p>My resume can be viewed here. Please feel free to right click the link and save a copy for yourself if you're interested.</p>
                            </div>
                        <div class="card-read-more">
                            <%= link_to " View Resume", image_path("resume.jpg"), :target => "_blank", :class => "btn btn-link btn-block" %>
                        </div><!-- end read more -->
                    </div>
                </div><!--end card -->
            </div><!-- end column div -->
        </div><!--end row -->
    </article> <!-- end homepage cards article within aboutme-content section -->

    <!--<div class="row">-->
    <!--    <a class="scroll-down3" href="#" address="true">-->
    <!--        <div class="arrow-scroll-btn"  data-toggle="tooltip" data-placement="top" title="Development Section" ></div>-->
    <!--    </a>-->
    <!--</div>-->

</section><!-- end aboutme-content section -->
 

app/views/static_pages/index.html.erb
<%= render 'landing' %><!-- landing page section -->
<%= render 'aboutme' %><!-- about me/contact section -->
<%= render 'sidebar' %><!-- sidebar / visible on all sections besides landing page. Not visible on secodary pages. -->

<div id="fill-in"></div><!--  div fills with rendered UI/UX and/or dev work sections.  -->

<%= link_to '', '/', :class => 'arrow-scroll-up hidden sectionScroll', :id => 'scrollup' %><!--  scroll to top arrow visible throughout all sections besides landing page section  -->
<%= render 'footer' %><!-- renders footer -->

app/views/static_pages/render_design.js.erb
$('#fill-in').html("<%= escape_javascript(render :partial => 'design') %>");

app/views/static_pages/render_dev.js.erb
$('#fill-in').html("<%= escape_javascript(render :partial => 'devWork') %>");